version: "3.9"

networks:
  default:
    name: docker-demo

services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "8402:8402"
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - redis
